import { fetchExternal } from "@/lib/services/external-fetch";
import nodemailer from "nodemailer";
import * as webPush from "web-push";
import { renderAlertEmailHtml } from "@/lib/services/email-template";
import { prisma } from "@/lib/db/prisma";

type AlertChannelSettings = {
  ntfyTopicUrl: string | null;
  ntfyAuthToken: string | null;
  ntfyEnabled: boolean;
  alertEmailTo: string | null;
  smtpHost: string | null;
  smtpPort: number | null;
  smtpUser: string | null;
  smtpPassword: string | null;
  smtpFrom: string | null;
  emailAlertsEnabled: boolean;
  webPushEnabled: boolean;
  // Whose devices to push to - VAPID keys themselves are instance-level as
  // of v2.0 and resolved inside sendWebPush.
  userId: string;
};

/**
 * ntfy's JSON publish API, not the simple API. The simple API puts the title in
 * a `Title` HEADER, and header values must be Latin-1 - alert titles are French
 * and routinely accented, so fetch throws on them. JSON string fields are
 * UTF-8-safe; that is the fix, not a smarter escape. Authorization stays a
 * header, since a bearer token is always ASCII.
 *
 * `icon`/`click` are set only when APP_URL is configured - both need a URL
 * ntfy's own servers can fetch. The icon points at Next's generated PNG route,
 * because ntfy accepts JPEG/PNG and not SVG.
 *
 * One fixed `tags` entry for every alert rather than one per kind: dispatchAlert
 * only ever receives a title/body pair from ~8 call sites, so per-kind tagging
 * means a new parameter through every one of them for something cosmetic.
 */export async function sendNtfyMessage(topicUrl: string, title: string, body: string, authToken: string | null = null): Promise<boolean> {
  try {
    const parsed = new URL(topicUrl);
    const topic = parsed.pathname.replace(/^\//, "");
    const appUrl = process.env.APP_URL?.replace(/\/$/, "");
    const payload: Record<string, unknown> = { topic, title, message: body, tags: ["bar_chart"] };
    if (appUrl) {
      payload.icon = `${appUrl}/icon`;
      payload.click = appUrl;
    }
    const headers: Record<string, string> = { "Content-Type": "application/json" };
    if (authToken) headers.Authorization = `Bearer ${authToken}`;
    const res = await fetchExternal(parsed.origin, { method: "POST", body: JSON.stringify(payload), headers });
    return res.ok;
  } catch (e) {
    console.error("Failed to send ntfy alert", e);
    return false;
  }
}

export async function sendEmail(
  config: { host: string; port: number; user: string | null; password: string | null; from: string; to: string },
  subject: string,
  text: string,
  html?: string
): Promise<boolean> {
  try {
    const transporter = nodemailer.createTransport({
      host: config.host,
      port: config.port,
      // 465 is the conventional implicit-TLS port; every other port (587,
      // 25, custom relays) uses STARTTLS instead - nodemailer's own
      // `secure` flag only controls the former.
      secure: config.port === 465,
      auth: config.user ? { user: config.user, pass: config.password ?? "" } : undefined,
    });
    // html is optional so existing/direct callers keep sending plain text
    // unchanged - only dispatchAlert below opts into the styled version.
    await transporter.sendMail({ from: config.from, to: config.to, subject, text, ...(html ? { html } : {}) });
    return true;
  } catch (e) {
    console.error("Failed to send alert email", e);
    return false;
  }
}

// Generated by the app on first use, never configured by a self-hoster, and
// they must stay STABLE forever after - regenerating silently invalidates every
// registered browser subscription. Instance-level, not per-user: a VAPID pair
// identifies this server to push services, not a person.
export async function getOrCreateVapidKeys(): Promise<{ publicKey: string; privateKey: string }> {
  const settings = await prisma.instanceSettings.upsert({
    where: { id: "singleton" },
    create: {},
    update: {},
    select: { vapidPublicKey: true, vapidPrivateKey: true },
  });
  if (settings.vapidPublicKey && settings.vapidPrivateKey) {
    return { publicKey: settings.vapidPublicKey, privateKey: settings.vapidPrivateKey };
  }
  const keys = webPush.generateVAPIDKeys();
  await prisma.instanceSettings.update({
    where: { id: "singleton" },
    data: { vapidPublicKey: keys.publicKey, vapidPrivateKey: keys.privateKey },
  });
  return keys;
}

// A 'https:' URL or 'mailto:' address identifying this app instance to push
// services, required by the VAPID spec - reuses APP_URL (same "leave blank
// for localhost use" convention already documented for GoCardless/ntfy
// above) when set, since it's already a real reachable URL for any instance
// that has one configured. Falls back to a fixed placeholder mailto -
// spec-required but not actually contacted by any push service in
// practice, so a generic value is fine for the common (no APP_URL) case.
const VAPID_SUBJECT = process.env.APP_URL?.replace(/\/$/, "") || "mailto:push@finalibaba.local";

// Reads its own subscriber list rather than taking one, which is what kept
// dispatchAlert's signature - and its ~10 call sites - unchanged when Web Push
// was added. Also prunes subscriptions the push service reports as gone
// (404/410); a dead one otherwise fails silently forever.
export async function sendWebPush(userId: string, title: string, body: string): Promise<boolean> {
  // Scoped to this user's own devices (v2.0) - previously every subscription
  // in the instance, which with several users would push one person's
  // financial alerts to everyone else's phone.
  const subscriptions = await prisma.pushSubscription.findMany({ where: { userId } });
  if (subscriptions.length === 0) return false;

  // Instance-level keypair (moved off UserSettings in v2.0), read here rather
  // than passed in so callers don't have to know where it lives.
  const settings = await prisma.instanceSettings.findUnique({
    where: { id: "singleton" },
    select: { vapidPublicKey: true, vapidPrivateKey: true },
  });
  if (!settings?.vapidPublicKey || !settings.vapidPrivateKey) return false;

  webPush.setVapidDetails(VAPID_SUBJECT, settings.vapidPublicKey, settings.vapidPrivateKey);
  const payload = JSON.stringify({ title, body });

  const staleIds: string[] = [];
  let successCount = 0;
  await Promise.allSettled(
    subscriptions.map(async (sub) => {
      try {
        await webPush.sendNotification({ endpoint: sub.endpoint, keys: { p256dh: sub.p256dh, auth: sub.auth } }, payload);
        successCount++;
      } catch (e) {
        const statusCode = e instanceof webPush.WebPushError ? e.statusCode : null;
        if (statusCode === 404 || statusCode === 410) {
          staleIds.push(sub.id);
        } else {
          console.error("Failed to send web push", e);
        }
      }
    })
  );

  if (staleIds.length > 0) {
    await prisma.pushSubscription.deleteMany({ where: { id: { in: staleIds } } });
  }
  return successCount > 0;
}

/**
 * Fans out to every channel that is both configured (non-blank) and enabled -
 * two separate gates, so someone with ntfy and email set up can still receive
 * through one. The toggles default to true, so an existing install keeps
 * firing. Each channel catches its own errors; allSettled is insurance.
 */
export async function dispatchAlert(settings: AlertChannelSettings, title: string, body: string): Promise<void> {
  const jobs: Promise<boolean>[] = [];

  if (settings.ntfyTopicUrl && settings.ntfyEnabled) {
    jobs.push(sendNtfyMessage(settings.ntfyTopicUrl, title, body, settings.ntfyAuthToken));
  }

  if (settings.alertEmailTo && settings.smtpHost && settings.smtpPort && settings.smtpFrom && settings.emailAlertsEnabled) {
    jobs.push(
      sendEmail(
        {
          host: settings.smtpHost,
          port: settings.smtpPort,
          user: settings.smtpUser,
          password: settings.smtpPassword,
          from: settings.smtpFrom,
          to: settings.alertEmailTo,
        },
        title,
        body,
        renderAlertEmailHtml(title, body)
      )
    );
  }

  // sendWebPush resolves the instance VAPID keypair and this user's own
  // subscriptions itself, so there's nothing left to gate on here beyond the
  // per-user toggle.
  if (settings.webPushEnabled) {
    jobs.push(sendWebPush(settings.userId, title, body));
  }

  await Promise.allSettled(jobs);
}
